language: java
sudo: false
jdk: openjdk8
dist: trusty
install: true
script: "./gradle/buildViaTravis.sh"
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
after_success:
- "./gradlew jacocoTestReport coveralls"
env:
  global:
  - secure: aEyaZZTFMdgbhSCG2r/9tlFySaTU6C/ibqNveCM32cixyHMvq9K0RhzCO75NbfDWSDf6rwRVsE86/pFrMJ9SNUkNKGE7n/51OqKqoLwjr2RdM2aptkl9eNGEmnpX8Po5B2Us3wpkmqgbZ6WO+0S2LOgbruef07taz3WDFfqzm1A=
  - secure: Ppt385XATGwtt2iVKHxmGcnwPgNt06SRN9fut7voouQVvMyTazhskBrHLi7eOsmt4HuNJZr1x/Crh3kP0//hIiI5/qj+x8BFaAtBZMYUOlF6SgQzmjC2zQaV3fkGshTRD1EC3ZEFVIoJtSkIM/NmAHLuii+fqNpH6vmcw62MrDQ=
  - secure: JAo7P7JqQYbEsoarHxQ9Veel0+3Ga9gZH9ZkjTo4lv9NSiqKO5v9IoM1Lx6t4limnivGct7gijk1Le4OBQ82Sf2DbtQdMvW6ovs6yKXXOxvh9qE8ZkK/MfVJ38m2ONiNSnJEJmZ+DZU2BNretVCXRcEBK7PCMvV+4HqAIx82FV0=
  - secure: S1T2VGl6oXurTwn21ky9NG8dfPFh2CFH5wwQp2ibvVktRRFYKE+72DZNEk7qsAOj5MfSYbHAe0EKAeC4FvWyH7ukBP0/4EaDUReRThmkLBC/59DjlisefLMkvW+up281Jt5/5MrhdmHCDyGDsL0H52NcdK5NZHV0hcZbwvFpJZQ=
  - secure: h/DajhG8tjxeskuE3jtuFGHSLLP8v8XMIZ2HM/dS02FPNvcy39myAXlhA1c66GEadX97mCZkPa6c3+Gf1UuZqm+lobzgyDkvz46X+KdPcQJHWkFTz+lU1EA0IG7Wc6x6AL7DWMJjeSsuTbuLIS9b7ug/7R6yr6hKIEgropjsxlw=
  - secure: bOnH23YtDJgdxZFAboAhy93Ng59Tb36RlTcSC0IR0z5MYvto2jN4D1xxHbc6MdHk8YiWMfKbc7g99KuzesWXC3/YsWC8wTdWBX1zkQsNFeB6037WwC7Wk+ZnUYzEEjaHVyK4xD5Db4L9hk3aKBu7UiRAX9YaGekq8E06rm0XwgI=
