name: ci
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup jdk 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v1
        id: gradle-cache
        with:
          path: $HOME/.gradle/caches
          key: gradle_local_cache
      - uses: actions/cache@v1
        id: gradle-wrapper-cache
        with:
          path: $HOME/.gradle/wrapper
          key: gradle_local_wrapper
      - name: Build with Gradle
        run: ./gradlew --info --stacktrace build
